INSERT ALL
    INTO TEACHES (pid, oid) VALUES (0,0)
    INTO TEACHES (pid, oid) VALUES (2,1)
    INTO TEACHES (pid, oid) VALUES (3,2)
    INTO TEACHES (pid, oid) VALUES (6,3)
    INTO TEACHES (pid, oid) VALUES (8,4)
    INTO TEACHES (pid, oid) VALUES (8,5)
    INTO TEACHES (pid, oid) VALUES (7,6)
    INTO TEACHES (pid, oid) VALUES (1,7)
    INTO TEACHES (pid, oid) VALUES (4,8)
    INTO TEACHES (pid, oid) VALUES (5,9)
    INTO TEACHES (pid, oid) VALUES (11,10)
    INTO TEACHES (pid, oid) VALUES (5,11)
    INTO TEACHES (pid, oid) VALUES (8,12)
    INTO TEACHES (pid, oid) VALUES (9,13)
    INTO TEACHES (pid, oid) VALUES (1,14)
    INTO TEACHES (pid, oid) VALUES (3,15)
    INTO TEACHES (pid, oid) VALUES (6,16)
    INTO TEACHES (pid, oid) VALUES (2,17)
    INTO TEACHES (pid, oid) VALUES (5,18)
    INTO TEACHES (pid, oid) VALUES (9,19)
    INTO TEACHES (pid, oid) VALUES (7,20)
    INTO TEACHES (pid, oid) VALUES (12,21)
    INTO TEACHES (pid, oid) VALUES (10,22)
    INTO TEACHES (pid, oid) VALUES (13,23)
SELECT * FROM dual;