INSERT ALL
    INTO HAS_MANDATORY (mid, cno) VALUES (0, 'CS026')
    INTO HAS_MANDATORY (mid, cno) VALUES (0, 'CS130')
    INTO HAS_MANDATORY (mid, cno) VALUES (0, 'CS154')
    INTO HAS_MANDATORY (mid, cno) VALUES (0, 'CS160')
    INTO HAS_MANDATORY (mid, cno) VALUES (0, 'CS170')

    INTO HAS_MANDATORY (mid, cno) VALUES (1, 'CS026')
    INTO HAS_MANDATORY (mid, cno) VALUES (1, 'CS130')
    INTO HAS_MANDATORY (mid, cno) VALUES (1, 'CS154')
    INTO HAS_MANDATORY (mid, cno) VALUES (1, 'CS160')
    INTO HAS_MANDATORY (mid, cno) VALUES (1, 'CS170')
SELECT * FROM dual;